- hosts: dokku
  become: yes
  vars_files:
    - secrets.yml
  tasks:
    - name: Install dependencies
      apt:
        name: "{{ packages }}"
      vars:
        packages:
          - git
          - wget

    - name: Install Dokku
      shell: |
        wget -NP . https://dokku.com/bootstrap.sh
        sudo DOKKU_TAG=v0.32.3 bash bootstrap.sh
      args:
        creates: /usr/bin/dokku

    - name: Check if SSH key already exists
      shell: dokku ssh-keys:list | grep "admin"
      register: ssh_key_check
      ignore_errors: yes

    - name: Add SSH key to Dokku
      shell: |
        echo "{{ public_key }}" | dokku ssh-keys:add admin
      when: ssh_key_check.rc != 0

    - name: Set global domain for Dokku
      shell: dokku domains:set-global danipolani.art

    - name: Install Dokku Let's Encrypt plugin
      shell: |
        dokku plugin:install https://github.com/dokku/dokku-letsencrypt.git
        dokku config:set --global DOKKU_LETSENCRYPT_EMAIL={{ email }}
      register: letsencrypt_plugin
      failed_when: letsencrypt_plugin.rc != 0 and "already installed" not in letsencrypt_plugin.stdout

    - name: Install Dokku Docker Registry plugin
      shell: dokku plugin:install https://github.com/dokku/dokku-registry.git
      register: docker_registry_plugin
      failed_when: docker_registry_plugin.rc != 0 and "already exists and is not an empty directory" not in docker_registry_plugin.stderr

    - name: Set Docker Hub environment variables
      shell: |
        dokku docker-options:add trainride deploy,run "-e DOCKER_USERNAME={{ docker_username }} -e DOCKER_PASSWORD={{ docker_password }}"
      vars:
        docker_username: "{{ docker_hub_username }}"
        docker_password: "{{ docker_hub_password }}"