- hosts: dokku
  become: yes
  vars:
    docker_image_tag: latest 
    docker_image: delael/trainride
  tasks:
    - name: Delete image
      shell: docker rmi delael/trainride:latest

    - name: Deploy to dokku
      shell: |
        dokku git:from-image trainride delael/trainride:latest
      register: dokku_output
      failed_when: >
        ('Image exists on host, skipping pull' not in dokku_output.stderr) and
        ('No changes detected, skipping git commit' not in dokku_output.stderr) and
        dokku_output.rc != 0

    - name: Rebuild in dokku
      shell: dokku ps:rebuild trainride
